services:
  stack_tavern:
    image: tavern
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  stack_tavern_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stack_tavern

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
